<?xml version="1.0"?>
<package format="3">
  <name>ublox_msg_filters</name>
  <version>0.0.0</version>
  <description>
    Time synchronize multiple uBlox messages to get a single callback
  </description>

  <maintainer email="khallenbeck@dataspeedinc.com">Kevin Hallenbeck</maintainer>
  <license>BSD</license>

  <author email="khallenbeck@dataspeedinc.com">Kevin Hallenbeck</author>
  <url type="website">http://ros.org/wiki/ublox</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rcpputils</depend>
  <depend>ublox_msgs</depend>
  <depend>message_filters</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>